# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DreamLister_v3' do
  use_frameworks!

  # Pods for DreamLister_v3
  pod 'IQKeyboardManagerSwift'

end
